apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/video-streaming-docker-default: "true"
        io.kompose.service: db
    spec:
      containers:
        - args:
            - --default-authentication-plugin=mysql_native_password
          env:
            - name: MYSQL_DATABASE
              value: video_streaming
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MySQL_ROOT_HOST
              value: localhost
            - name: MySQL_USER
              value: express
            - name: SECRET
              value: a09fjw091jfi310
          image: cearis/mysql:latest
          livenessProbe:
            exec:
              command:
                - mysqladmin ping -h 127.0.0.1 -u $MYSQL_USER --password=$MYSQL_PASSWORD
            failureThreshold: 30
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
          name: db
          ports:
            - containerPort: 3306
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
