apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  selector:
    matchLabels:
      app: auth
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - env:
            - name: ACCESS_TOKEN_SECRET
              value: 3e9af42de397cfc9387a06972c28c23a1ac7e9a60fb6dc1f05295bc6057baf500672d4a13db5d04ea84bbc4c5679164a7723f3d49f516bb73dc3df6e3b768c8e
          image: cearis/authimage:latest
          imagePullPolicy: IfNotPresent
          name: auth
          resources: {}
      restartPolicy: Always
