apiVersion: v1
kind: PersistentVolume
metadata:
  name: fs-data
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fs-data
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
