apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - args:
            - --default-authentication-plugin=mysql_native_password
          env:
            - name: MYSQL_DATABASE
              value: video_streaming
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MySQL_ROOT_HOST
              value: localhost
            - name: MySQL_USER
              value: express
            - name: SECRET
              value: a09fjw091jfi310
          image: mysql:8.0
          livenessProbe:
            exec:
              command:
                - mysqladmin ping -h 127.0.0.1 -u $MYSQL_USER --password=$MYSQL_PASSWORD
            failureThreshold: 30
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
          name: db
          ports:
            - containerPort: 3306
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
            - mountPath: /docker-entrypoint-initdb.d
              name: db-claim1
      restartPolicy: Always
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data
        - name: db-claim1
          configMap:
            name: data-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: data-config
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS video_streaming;
    USE video_streaming;
    CREATE TABLE IF NOT EXISTS video_library (video_id INT NOT NULL AUTO_INCREMENT, video_title VARCHAR(255) NOT NULL, video_path VARCHAR(255) NOT NULL, PRIMARY KEY (video_id));
    CREATE TABLE IF NOT EXISTS users (user VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (user));
    CREATE USER 'express'@'%' IDENTIFIED BY 'password';
    GRANT ALL PRIVILEGES ON video_streaming.video_library TO 'express'@'%';
    GRANT ALL PRIVILEGES ON video_streaming.users TO 'express'@'%';
    FLUSH PRIVILEGES;
