version: '3'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      SECRET: a09fjw091jfi310
      MYSQL_DATABASE: video_streaming
      MYSQL_ROOT_PASSWORD: password
      MySQL_ROOT_HOST: "localhost"
      MySQL_USER: express
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 3306
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 30
  auth:
    image: myauthimage
    build:
      context: ./auth
      dockerfile: Dockerfile
    environment:
      ACCESS_TOKEN_SECRET: 3e9af42de397cfc9387a06972c28c23a1ac7e9a60fb6dc1f05295bc6057baf500672d4a13db5d04ea84bbc4c5679164a7723f3d49f516bb73dc3df6e3b768c8e
    depends_on:
      upload:
        condition: service_started
  upload:
    image: myuploadimage
    build:
      context: ./upload
      dockerfile: Dockerfile
    environment:
      SECRET: a09fjw091jfi310
      DB_HOST: db
      DB_PASSWORD: password
      ACCESS_TOKEN_SECRET: 3e9af42de397cfc9387a06972c28c23a1ac7e9a60fb6dc1f05295bc6057baf500672d4a13db5d04ea84bbc4c5679164a7723f3d49f516bb73dc3df6e3b768c8e
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - data:/mnt/data
  file_system:
    build: ./file_system
    volumes:
      - data:/mnt/data
    environment:
      SECRET: a09fjw091jfi310
  streaming:
    image: mystreamingimage
    build:
      context: ./streaming
      dockerfile: Dockerfile
    environment:
      SECRET: a09fjw091jfi310
      DB_HOST: db
      DB_PASSWORD: password
      FILE_SYSTEM_HOST: file_system
      ACCESS_TOKEN_SECRET: 3e9af42de397cfc9387a06972c28c23a1ac7e9a60fb6dc1f05295bc6057baf500672d4a13db5d04ea84bbc4c5679164a7723f3d49f516bb73dc3df6e3b768c8e
    volumes:
      - data:/mnt/data
    depends_on:
      db:
        condition: service_healthy
  web:
    image: mynginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - static-data:/usr/share/nginx/html
      - nginx-conf:/etc/nginx/sites-enabled
    depends_on:
      streaming:
        condition: service_started
      upload:
        condition: service_started
      auth:
        condition: service_started
    environment:
      ACCESS_TOKEN_SECRET: a09fjw091jfi310
volumes:
  mysql-data: {}
  nginx-conf: {}
  static-data: {}
  data: {}